version: 2
jobs:
   build:
     docker:
       - image: circleci/python:2.7
     steps:
       - checkout
       - run:
            name: update apt
            command: 'sudo apt-get update'
       - run:
            name: Run install.sh
            command: 'cd setup/ && sudo -E -H ./install.sh'
       - run:
            name: Start Empire
            command: 'sudo ./empire --headless &'
       - run:
            name: modify kernel behavior for TIME_WAIT connections
            command: 'sudo sysctl net.ipv4.tcp_tw_recycle=1'
       - run:
            name: REST API test
            command: 'cd .circleci/ && python test.py'
