version: 2
jobs:
   build:
     docker:
       - image: circleci/python:2.7.13
     environment:
       - STAGING_KEY: "RANDOM"
     steps:
       - checkout
       - run:
            name: Run install.sh
            command: 'cd setup/ && sudo ./install.sh'
