version: 2
jobs:
   build:
     docker:
       - image: circleci/python:2.7
     steps:
       - checkout
<<<<<<< HEAD
       - run: echo "hello world"
=======
       - run:
            name: update apt
            command: 'sudo apt-get update'
       - run:
            name: Run install.sh
            command: 'cd setup/ && sudo -E -H ./install.sh'
       - run:
            name: Start Empire
            command: 'sudo ./empire --headless &'
       - run:
            name: Stop Empire
            command: "sleep 60 && sudo kill $(ps -ef | grep '[p]ython ./empire --headless' | awk '{print $2}')"
>>>>>>> c05acf2... updated yml file
